### ISSUE TITLE
Tweak to Brutal Smash advice

### ISSUE THREAD

**Issue by SabreCat** [Alys/tools-for-habitrpg#30]
On the skills page, the listing for Brutal Smash advises: "If you want to use the skill to damage the boss but don't want to adjust the rewards you would receive for a task, then cast the skill on your bluest task".

An even better tactic, guaranteed not to affect your task output except in highly unusual circumstances, is to fire Brutal Smash at a completed To-Do!

**Comment by Alys** [comment]
Ha. Good point! Thanks. I'll put that in the next release.
