### ISSUE TITLE
Request: Equipment Table: Change Class column value from 'special' to 'kickstarter' or 'contributor' for some items

### ISSUE THREAD

**Issue by mister-clean** [Alys/tools-for-habitrpg#52]
Since this table is used by players to build a plan for useful equipment loadouts, it would be helpful to have the ability to filter out items that are officially retired and no longer acquirable (e.g. Kickstarter backer items). To that end, I recommend adding a new value of "kickstarter" (or "backer") to the "Class" column, which would replace the value of "special" for all items that are only available to Kickstarter backers. I realize that the Item name for these items is largely already hyperlinked to its respective Kickstarter/Seasonal page, but an unambiguous filter in an already-existing column would be more useful than the default value of "special".

To a similar end, I recommend adding a new value of "contributor" to the "Class" column, which would replace the value of "special" for all Contributor Rewards items. This will help players identify which items are not attainable through regular gameplay. It can also serve to raise awareness of (and participation in) contributor activities.

These recommendations avoid the creation of a new column, as the table seems to be at an optimal column capacity. I recognize that some items may qualify both as "class-exclusive" items that confer a Class Bonus _and_ as Armoire/Mystery/Take This/Kickstarter/Contributor items, and being able to identify both of these qualities for these items within the table would be valuable. I just don't have any recommendations on how to elegantly implement this without adding a new column ("Obtain", or something).

Thanks,
GitHub: @edward-cook
Habitica Fandom: @kyylyew

**Comment by Alys** [comment]
I'm so sorry I didn't reply to this when you posted it!  I have a backlog of everything. :(

I really like the idea of changing "special" to "kickstarter" and "contributor" for those kinds of items. I've added it to the code and it will be in the wiki page in a few minutes if all goes well!

**Comment by Alys** [comment]
There's a slight catch: the filtering no longer works in https://habitica.fandom.com/wiki/Equipment_Table but I think that's because of some recent changes to Fandom sites. I'll look into getting it working again.

I noticed it before I uploaded the changes from this commit so it's not caused by the new code.

**Comment by mister-clean** [comment]
Awesome. Thanks Alys. I see the changes.

 

If I find other “special” items that could be changed to “Kickstarter” or “Contributor” should I drop the change request in GitHub again? Since the labels are part of the code?

 

Good luck with restoring the filter functionality.

 

Thanks,

Ed

**Comment by Alys** [comment]
> If I find other “special” items that could be changed to “Kickstarter” or “Contributor” should I drop the change request in GitHub again? 

Yes, that would be great!

Thanks! :)
